/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp manifest.xml --adaptor ServerAdaptor --proxy ClientProxy
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "ClientProxy.h"

/*
 * Implementation of interface class MeTimschneebergerJdsp4linuxGuiInterface
 */

MeTimschneebergerJdsp4linuxGuiInterface::MeTimschneebergerJdsp4linuxGuiInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

MeTimschneebergerJdsp4linuxGuiInterface::~MeTimschneebergerJdsp4linuxGuiInterface()
{
}

/*
 * Implementation of interface class MeTimschneebergerJdsp4linuxServiceInterface
 */

MeTimschneebergerJdsp4linuxServiceInterface::MeTimschneebergerJdsp4linuxServiceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

MeTimschneebergerJdsp4linuxServiceInterface::~MeTimschneebergerJdsp4linuxServiceInterface()
{
}

