/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp manifest.xml -a serveradaptor -p clientproxy
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SERVERADAPTOR_H
#define SERVERADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T>
class QList;
template<class Key, class Value>
class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface me.timschneeberger.jdsp4linux.Gui
 */
class GuiAdaptor :
	public QDBusAbstractAdaptor
{
	Q_OBJECT
	Q_CLASSINFO("D-Bus Interface",     "me.timschneeberger.jdsp4linux.Gui")
	Q_CLASSINFO("D-Bus Introspection", ""
	            "  <interface name=\"me.timschneeberger.jdsp4linux.Gui\">\n"
	            "    <method name=\"show\"/>\n"
	            "    <method name=\"hide\"/>\n"
	            "    <method name=\"raiseWindow\"/>\n"
	            "  </interface>\n"
	            "")

public:
	GuiAdaptor(QObject *parent);
	virtual ~GuiAdaptor();

public: // PROPERTIES

public Q_SLOTS: // METHODS
	void hide();
	void raiseWindow();
	void show();

Q_SIGNALS: // SIGNALS
};

#endif