/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp manifest.xml --adaptor ServerAdaptor --proxy ClientProxy
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SERVERADAPTOR_H
#define SERVERADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface me.timschneeberger.jdsp4linux.Gui
 */
class GuiAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "me.timschneeberger.jdsp4linux.Gui")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"me.timschneeberger.jdsp4linux.Gui\">\n"
"    <method name=\"raiseWindow\"/>\n"
"  </interface>\n"
        "")
public:
    GuiAdaptor(QObject *parent);
    virtual ~GuiAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void raiseWindow();
Q_SIGNALS: // SIGNALS
};

/*
 * Adaptor class for interface me.timschneeberger.jdsp4linux.Service
 */
class ServiceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "me.timschneeberger.jdsp4linux.Service")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"me.timschneeberger.jdsp4linux.Service\">\n"
"    <property access=\"read\" type=\"s\" name=\"SamplingRate\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"AudioFormat\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"IsProcessing\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"CoreVersion\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"AppVersion\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"AppFlavor\"/>\n"
"    <method name=\"getKeys\">\n"
"      <arg direction=\"out\" type=\"as\" name=\"keys\"/>\n"
"    </method>\n"
"    <method name=\"get\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"key\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"getAll\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"kvpairs\"/>\n"
"    </method>\n"
"    <method name=\"set\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"key\"/>\n"
"      <arg direction=\"in\" type=\"v\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"setAndCommit\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"key\"/>\n"
"      <arg direction=\"in\" type=\"v\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"commit\"/>\n"
"    <method name=\"getPresets\">\n"
"      <arg direction=\"out\" type=\"as\" name=\"presets\"/>\n"
"    </method>\n"
"    <method name=\"loadPreset\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"    </method>\n"
"    <method name=\"savePreset\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"    </method>\n"
"    <method name=\"deletePreset\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ServiceAdaptor(QObject *parent);
    virtual ~ServiceAdaptor();

public: // PROPERTIES
    Q_PROPERTY(QString AppFlavor READ appFlavor)
    QString appFlavor() const;

    Q_PROPERTY(QString AppVersion READ appVersion)
    QString appVersion() const;

    Q_PROPERTY(QString AudioFormat READ audioFormat)
    QString audioFormat() const;

    Q_PROPERTY(QString CoreVersion READ coreVersion)
    QString coreVersion() const;

    Q_PROPERTY(bool IsProcessing READ isProcessing)
    bool isProcessing() const;

    Q_PROPERTY(QString SamplingRate READ samplingRate)
    QString samplingRate() const;

public Q_SLOTS: // METHODS
    void commit();
    void deletePreset(const QString &name);
    QString get(const QString &key);
    QString getAll();
    QStringList getKeys();
    QStringList getPresets();
    void loadPreset(const QString &name);
    void savePreset(const QString &name);
    void set(const QString &key, const QDBusVariant &value);
    void setAndCommit(const QString &key, const QDBusVariant &value);
Q_SIGNALS: // SIGNALS
};

#endif
